language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head

env:
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=3.2.22"
  - "RAILS_VERSION=4.0.13"
  - "RAILS_VERSION=4.1.14"
  - "RAILS_VERSION=4.2.5"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
